### PR TITLE
leader election is now modified bully. 

### PR DESCRIPTION
**Pull request by ErickPower**
Changed from finding quietest server.
Change located in UsageChecker.java/leaderElection()

### CODE REVIEW

**Comment by NickKohse** [comment]
This looks good but we'll need some other code changes to make it work. I had to change some stuff in balancer worker to make the system work initially, mainly stop using the getQuietPort function because it kept returning 0. If you're sure this works around here: https://github.com/Christopher-Baker/CPSC559Project/blob/master/src/CPSC559/BalancerWorker.java#L154 will need to be changed to call this code.

**Comment by NickKohse** [comment]
I think this wil be good to merge now once you switch balancer worker back to using your functions instead of the hacks I did to make it work.

**Comment by ErickPower** [comment]
Should be good. Just need @NickKohse to test once possible. Also, I only saw hacks in BalanceWorker.java. Is that the only location these hacks existed?

**Comment by NickKohse** [comment]
> Should be good. Just need @NickKohse to test once possible. Also, I only saw hacks in BalanceWorker.java. Is that the only location these hacks existed?

Yeah you've fixed all ones I was thinking of, Ill try to take a look later this afternoon.

**Pull request merged**
